### ISSUE TITLE
trace output for CMD 

### ISSUE THREAD

**Issue by janondrusek** [BastilleBSD/rocinante#6]
`CMD` does not output any trace (unlike e.g. `CP,` which is using `-v` unless `-q` is specified).

```
$ cat base/Bastillefile
CMD /bin/ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime

CP etc /
CP root /

$ rocinante template base # notice [CMD] trace is completely missing, only exit code 0 gets printed
[TEMPLATE]:
Applying template: base...

0

[CP]:
base/etc -> /etc
base/etc/ttys -> /etc/ttys

[CP]:
base/root -> /root
base/root/.hushlogin -> /root/.hushlogin
```

1. the `[CMD]` should be shown
2. ideally `sh -x` would print the command being executed, unless `-q`

**Comment by cedwards** [comment]
Thank you for contributing this feature. Changes are available in the 0.1.20220714 release.
